---
prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/samvera/bixby/v5.0.2/bixby_default.yml"
    path: "bixby_default.yml"
  - url: "https://raw.githubusercontent.com/samvera/bixby/v5.0.2/bixby_rails_enabled.yml"
    path: "bixby_rails_enabled.yml"
  - url: "https://raw.githubusercontent.com/samvera/bixby/v5.0.2/bixby_rspec_enabled.yml"
    path: "bixby_rspec_enabled.yml"
engines:
  brakeman:
    enabled: true
  duplication:
    enabled: false
  eslint:
    enabled: true
    config:
      extensions:
        - .es6
      ignore_warnings: true
  fixme:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-1-48-1
    config:
      file: .rubocop.cc.yml
    checks:
      Rubocop/Metrics/AbcSize:
        enabled: false
      Rubocop/Metrics/BlockLength:
        enabled: false
      Rubocop/Style/StringLiterals:
        enabled: false        
  coffeelint:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.js"
  - "**.es6"
  - "**.coffee"
  - "**.rake"
  - "**.scss"
exclude_paths:
- config/
- db/
- spec/
- vendor/
- app/migration/
