version: '2'

volumes:
  db-test:
  streaming-test:
  fedora-test:
  solr-test:
  npms:
  gems:

services:
  db:
    image: postgres:10-alpine
    volumes:
      - db-test:/data
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_DB=avalon
  fedora:
    image: avalonmediasystem/fedora:4.7.5
    depends_on:
      - db
    volumes:
      - fedora-test:/data
    environment:
     - JAVA_OPTIONS=-Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json -Dfcrepo.home=/data
  solr:
    image: solr:6.6.4-alpine
    volumes:
      - ./solr/config:/opt/solr/avalon_conf
      - solr-test:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
  # redis:
  #   image: redis:alpine
  avalon:
    image: avalonmediasystem/avalon:6.x-dev
    command: "/rails_init-test.sh"
    depends_on:
      - db
      - fedora
      - solr
      # - redis
    environment:
      - APP_NAME=avalon
      - SETTINGS__DOMAIN=http://test.host/
      - AVALON_BRANCH=develop
      - AVALON_DB_PASSWORD=avalondb
      - BASE_URL=http://test.host
      - CONTROLLED_VOCABULARY=config/controlled_vocabulary.yml
      - DATABASE_URL=postgres://postgres@db/avalon
      - SETTINGS__DROPBOX__PATH=/masterfiles/dropbox
      - SETTINGS__DROPBOX__UPLOAD_URI=./masterfiles/dropbox
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY=delete
      - MATTERHORN_URL=http://matterhorn_system_account:CHANGE_ME@matterhorn:8080/
      - SETTINGS__MATTERHORN__MEDIA_PATH=/masterfiles
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=test
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - SECRET_KEY_BASE=abcd
      - SOLR_URL=http://solr:8983/solr/avalon
      - SETTINGS__STREAMING__CONTENT_PATH=/streamfiles
      - SETTINGS__STREAMING__STREAM_DEFAULT_QUALITY=medium
      - SETTINGS__STREAMING__HTTP_BASE=http://localhost:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL=20
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
    volumes:
      - ./masterfiles:/masterfiles
      - gems:/home/app/gems
      - npms:/home/app/node_modules
      - .:/home/app/avalon
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
