{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "avalon.serviceAccountName" . }}
  labels:
{{ include "avalon.labels" . | nindent 4 }}
{{- end -}}
