---
- :name: Indiana University
  :logo: iu_logo.png
  :provider: :cas
  :params:
    :host: cas.iu.edu
    :login_url: /cas/login
    :service_validate_url: /cas/validate
    :logout_url: /cas/logout
    :ssl: true
