# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8268df0c1b5843bec6d0e6e1095b187766ff6a8f9c1edd4360588d357253fac09c95aebc715f25cb3ecfdf45cfb2da6c1c033149e93a363f3808da67b0b8ab09

test:
  secret_key_base: f589c05f948f5760c95e5c60fa0fb325a9fa7e8c9ba8190d22b8ff868927215dd4e5252227245dd26b4e98c9441ce5ef34a14ea25b2170191cb3f5ddad6c5755

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
