local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

minio:
  service: S3
  access_key_id: <%= ENV['SETTINGS__MINIO__ACCESS'] %>
  secret_access_key: <%= ENV['SETTINGS__MINIO__SECRET'] %>
  region: <%= ENV['AWS_REGION'] %>
  bucket: 'supplementalfiles'
  endpoint: <%= ENV['SETTINGS__MINIO__ENDPOINT'] %>
  force_path_style: true