#!/usr/bin/env bash

# Detects the Avalon version by grepping
# through config/application.rb
# Version should be sematic format like this:
# major.minor.patch.build
# Must have at least major.minor
# Supported examples:
# 7.3
# 7.3.0
# 7.3.0.15

SCRIPT_PATH=`dirname "$(readlink -f "${BASH_SOURCE[0]}")"`

#VERSION=`grep -Pv "^\s*\#" "${SCRIPT_PATH}/../config/application.rb" | grep "VERSION" | grep -Po "\d+\.\d+\.\d+(\.\d+)?"`

VERSION=`grep -Pv "^\s*\#" "${SCRIPT_PATH}/../config/application.rb" | grep "VERSION" | grep -Po "\d+\.\d+(\.\d+)*"`
echo $VERSION
