#!/usr/bin/env bash

SCRIPT_PATH=`dirname "$(readlink -f "$0")"`

VERSION=`grep -Pv "^\s*\#" "${SCRIPT_PATH}/../config/application.rb" | grep "VERSION" | grep -Po "\d+\.\d+\.\d+(\.\d+)?"`
echo $VERSION

