#!/usr/bin/env bash

# Copyright 2011-2022, The Trustees of Indiana University and Northwestern
#   University.  Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
# 
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed
#   under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#   CONDITIONS OF ANY KIND, either express or implied. See the License for the
#   specific language governing permissions and limitations under the License.
# ---  END LICENSE_HEADER BLOCK  ---

validate_image_name ( ) {
  name=$1
  pattern='^[-.0-9a-zA-Z,_/:]+$'
  [[ $name =~ $pattern ]]
}

ACTION=$1
if [ $ACTION != "--dry-run" ] && [ $ACTION != "--execute" ]; then
  echo "No action specified; must specifiy --dry-run or --execute as the first parameter"
  exit 1
fi
SOURCE=$2
DESTINATION=$3
TAGS_CSV=$4
TAGS=()
COMMAND_BASE="podman image push "

pattern='^[-.0-9a-zA-Z,_/:]+$'

format_err=""
if [[ ! $SOURCE =~ $pattern ]]; then
  format_err+="\n  SOURCE\n"
fi

if [[ ! $DESTINATION =~ $pattern ]]; then
  format_err+="  DESTINATION\n"
fi

if [[ ! $TAGS_CSV =~ $pattern ]]; then
  format_err+="  TAGS\n"
fi

if [[ $format_err != "" ]]; then
  echo -e "Argument formats incorrect: ${format_err}"
  exit 2
fi

IFS=, TAGS=($TAGS_CSV)
IFS=" "

if [ "${TAGS}" == "" ]; then
  echo "No tags found; exiting"
  exit 1
fi

for tag in "${TAGS[@]}"; do
  command="${COMMAND_BASE} ${SOURCE} ${DESTINATION}:${tag}"
  if [ $ACTION == "--execute" ]; then
    echo "Pushing image; executing command ..."
    echo $command
    `$command`
    success=$?
    if [ $success != 0 ]; then
      echo "FAILED; error code: $success"
      exit $success
    fi
  else
    echo $command
  fi

done
