#!/usr/bin/env bash

SOURCE=$1
DESTINATION=$2
TAGS_CSV=$3
TAGS=()
COMMAND_BASE="podman image push "

IFS=, TAGS=($TAGS_CSV)
IFS=" "

echo "TAGS"
echo ${TAGS[@]}

if [ "${TAGS}" == "" ]; then
  echo "No tags found; exiting"
  exit 1
fi

for tag in "${TAGS[@]}"; do
  echo "tag '$tag'"
  #exit 1 if $tag.empty?
  command="${COMMAND_BASE} ${SOURCE} ${DESTINATION}:${tag}"
  echo "pushing image ... command:"
  echo $command
  #`$command`
done
