#!/bin/sh
#
# Usage: locking_runner process_name command arg arg arg...
#

SEMAPHORE=$1
LOCKFILE=tmp/pids/$SEMAPHORE

if ( [ -e $LOCKFILE ] && ! kill -0 $(< $LOCKFILE) ) 2> /dev/null;
then
  echo "$0: Deleting stale lock file: $LOCKFILE"
  rm -f "$LOCKFILE";
fi

shift

if ( set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; 
then
  trap 'rm -f "$LOCKFILE"; exit 255' INT TERM EXIT
  "$@" || true #run the command
fi
